name: spotify_api
version: 1.0.1
description: OpenAPI API client
environment:
    sdk: ">=2.3.0 <3.0.0"
dependencies:
    dio: ^3.0.10
    built_value: ^8.0.0
    built_collection: ^5.0.0
dev_dependencies:
    built_value_generator: ^8.0.0
    build_runner: ^1.11.1

